version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.0.2
    - 9.1.0
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.168
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: highlight.js
    versions:
    - 9.18.5
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: acorn
    versions:
    - 5.7.4
